# SEO Values
title: Gustav PHP README
tagline: This is my first PHP project! 
description: This is my first PHP project! 
url: https://GILLESMaster.github.io/Gustav-PHP/
twitter: https://twitter.com/GustavoSchip
logo: https://raw.githubusercontent.com/GILLESMaster/Gustav-PHP/main/public/favicon.ico

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: GILLESMaster
  owner_url: https://github.com/GILLESMaster
  repository_url: https://github.com/GILLESMaster/Gustav-PHP

show_downloads: true
show_header: true
remote_theme: "pages-themes/time-machine@v0.2.0"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
